### ISSUE TITLE
Heroku says plugin not found

### ISSUE THREAD

**Issue by xaphod** [jemcode/heroku-postico#1]
So, I did `npm install heroku-postico` (success), then 

```
$ heroku plugins:install heroku-postico --app myapp
Installing plugins heroku-postico --app myapp... !
 ▸    Plugin not found
```

What am I forgetting? thanks.

**Comment by rikkipitt** [comment]
Hi @xaphod, it looks like you're installing it incorrectly. This plugin is an extension of the heroku cli, i.e. a global tool rather than one per app. It's not intended to be installed with npm either...

To install, simply run:

```
heroku plugins:install heroku-postico
```

From there on out, you can quickly open app Postgres connections in Postico using the instructions found in the readme. Let me know if this helps!

**Comment by xaphod** [comment]
When I run `heroku plugins:install heroku-postico`, the heroku-cli it says plugin not found.

**Comment by rikkipitt** [comment]
Do you have the latest heroku-cli? I just tested the command and it worked fine...

**Comment by xaphod** [comment]
Sorry, I figured it out -- sheer idiocy on my side... Apologies and thanks!

**Comment by rikkipitt** [comment]
@xaphod no worries at all, glad you got it sorted. Enjoy it!
